# Engagement - NOTES 

Here is Eagle IO's definition of engagement:

A state of personal immersion in work characterized by enthusiasm, dedication, and personal investment, expressed cognitively, affectively, and behaviorally in the proactive pursuit of advancing organizational goals.

This definition was created by Eagle IO on Spring 2019, and modified by Dr. Kulas and Renata on Fall 2019 to include the four dimensions of Fulfillment, Absorbtion, Dedication, and Vigor. 

## Feb 20.2020
Decided to operationalize fullfillment as an outcome of engagement rather than a definitional element 
Considering removing fulfillment

Reconceptualized as an OUTCOME of engagement (2/20) 

Fulfillment: finding meaning in one's work, while having a sense of autonomy, growth, usefulness, achievement, and feeling appreciated by org. [Satisfaction(?)]


## Definitions as of 02.20.2020

Absorption:  
being fully concentrated and happily immersed in ones work (time passes quickly and has difficulty detaching from ones work; Schaufeli et al., 2002)

02.24.2020
changind fedinition to:
being fully immersed in ones work (time passes quickly and has difficulty detaching from ones work)


Dedication/Commitment: 
being strongly involved in one's work and experiencing a sense of enthusiasm, inspiration, pride, and challenge. (Schaufeli et al., 2002) Identifying as an organizational member/ambassador

include identification with the organization, a sense of "oneness"
seeking continuous leanring and improvement 
getting rid of challenge altogether
moving inspiration and pride to other categories 

2.24.2020
definition of dedication changing to:
seeking continous imporvement and demonstrating initiative 

Vigor: 
investing consistent effort, persistence, energy, and mental resilience while working (Schaufeli et al., 2002)
maybe add enthusiasm here as well 

2.24.2020
chaning definition of Vigor: 
Experiencing persistent levels of energy and enthusiasm while working 

********
potential to change from affective, cognitive, and behavioral to whether their engagement comes from content/satisfaction with the organization or the people they work with. 

******** 

After completing individual Q-sorts (Kulas and Renata) we decided to revisit the definitions and build them up a little to make the diference between them more noticible. 

## Definitions as of 5/19/2020

Absorption: Being fully immersed in one’s work, where time passes quickly and one has difficulty detaching from work tasks

Vigor: Experiencing persistent levels of energy, effort, and enthusiasm while working

Dedication: Experiencing pride and challenge in ones work, as well as strong feelings of support from and loyalty toward the organization

With these definitions we ordered all the items according to the ones we individually selected for each category and created an item bank with the remaining items. Together we placed the items in the bank into the agreed upon categories. 

Next steps: 
Place items in the DAV categories into the ABC categories 

