# References

@eagly_psychology_1993
@simpson_engagement_2009
[@harter_business_2002; @kahn_psychological_1990; @leiter_areas_2003; @R-base; @R-rmarkdown; @rothbard_enriching_2001; @saks_antecedents_2006; @schaufeli_measurement_2002; @simpson_engagement_2009]

<div id="refs"></div>

# (APPENDIX) Appendix {-} 

# Timeline of events

Here is Eagle IO's initial definition of engagement (Spring 2019):

A state of personal immersion in work characterized by enthusiasm, dedication, and personal investment, expressed cognitively, affectively, and behaviorally in the proactive pursuit of advancing organizational goals.

This definition was created by Eagle IO Spring 2019, and modified by Dr. Kulas and Renata Fall 2019 to include the four dimensions of Fulfillment, Absorbtion, Dedication, and Vigor. 

## Feb 20.2020 (Considering removing fulfillment)

*Fulfillment*: finding meaning in one's work, while having a sense of autonomy, growth, usefulness, achievement, and feeling appreciated by org. [Satisfaction(?)]

Decided to operationalize fullfillment as an *outcome* of engagement rather than a definitional element 

## Definitional amendments as of 02.24.2020

*Absorption*: being fully concentrated and happily immersed in ones work (time passes quickly and has difficulty detaching from ones work; Schaufeli et al., 2002)

*Dedication/Commitment*: being strongly involved in one's work and experiencing a sense of enthusiasm, inspiration, pride, and challenge. (Schaufeli et al., 2002) Identifying as an organizational member/ambassador

include identification with the organization, a sense of "oneness"
seeking continuous leanring and improvement 
getting rid of challenge altogether
moving inspiration and pride to other categories 

*dedication*: seeking continous imporvement and demonstrating initiative 

*Vigor*: investing consistent effort, persistence, energy, and mental resilience while working (Schaufeli et al., 2002)
maybe add enthusiasm here as well 

*Vigor*: Experiencing persistent levels of energy and enthusiasm while working 

********
potential to change from affective, cognitive, and behavioral to whether their engagement comes from content/satisfaction with the organization or the people they work with. 

******** 

After completing individual Q-sorts (Kulas and Renata) we decided to revisit the definitions and build them up a little to make the difference between them more noticeable. 

## Definitions as of 5/19/2020

*Absorption*: Being fully immersed in one’s work, where time passes quickly and one has difficulty detaching from work tasks

*Vigor*: Experiencing persistent levels of energy, effort, and enthusiasm while working

*Dedication*: Experiencing pride and challenge in ones work, as well as strong feelings of support from and loyalty toward the organization

With these definitions we ordered all the items according to the ones we individually selected for each category and created an item bank with the remaining items. Together we placed the items in the bank into the agreed upon categories. 

# Items

After content validation, there was a dearth of items within some of the Affective, Cognitive, or Behavioral item groupings. We generated additional candidates at this point and have these items [located here](https://docs.google.com/document/d/1whB4Ve4aDDl3bxx3dIlloouTDy1ScCcxrT3gK6s9DyU/edit?usp=sharing) (Montclair State University e-mail needed to access)

# Pilot conditions {#pilot2}

Our four item orderings were:

```{r cond1, echo=FALSE, warning=FALSE, message=FALSE}


cond1 <- read.csv("cond1.csv")
cond2 <- read.csv("cond2.csv")
cond3 <- read.csv("cond3.csv")
cond4 <- read.csv("cond4.csv")

library(kableExtra)


kable(cond1) 
kable(cond2) 
kable(cond3) 
kable(cond4) 

```

